# .appveyor.yml

# Build version
version: '1.0.{build}'

# Use the latest available toolchain
image: Visual Studio 2019

# fetch repository as zip archive
shallow_clone: true

# PRs do not increment the build number
pull_requests:
  do_not_increment_build_number: true

# Build configurations
configuration: Release

# Default environment variables
environment:
  _IS_BUILD_CANARY: false
  _RELEASE_NAME: bgfx
  # Use Python 3.x
  PYTHON: "C:\\Python38-x64"
  PYTHON_VERSION: "3.8.x"
  PYTHON_ARCH: "64"

install:
  #- git clone --recurse-submodules https://github.com/bkaradzic/bgfx.git
  #- git clone --recurse-submodules https://github.com/bkaradzic/bx.git
  #- git clone --recurse-submodules https://github.com/bkaradzic/bimg.git
  - md bgfx\include
  - cd bgfx
  #- ..\bx\tools\bin\windows\genie --with-tools vs2019

# Prepare Cpp environment
before_build:
  - cmd: |
      set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq "true" -and $env:APPVEYOR_REPO_TAG_NAME) {
        $env:APPVEYOR_BUILD_VERSION = $env:APPVEYOR_BUILD_VERSION.Substring(0,$env:APPVEYOR_BUILD_VERSION.LastIndexOf('.')) + ".0"
        $env:_RELEASE_NAME = $env:_RELEASE_NAME + "-v" + $env:APPVEYOR_BUILD_VERSION
      } else {
        $env:_RELEASE_NAME = $env:_RELEASE_NAME + "-Canary"
        $env:APPVEYOR_REPO_TAG_NAME = "canary"
        $env:_IS_BUILD_CANARY = "true"
      }

#build:
#  project: bgfx/.build/projects/vs2019/bgfx.

build_script:
  - md .build\win32_vs2019\bin
  - md .build\win32_vs2019\obj
  - touch .build\win32_vs2019\bin\test.lib
  - touch .build\win32_vs2019\bin\test.pdb
  - touch .build\win32_vs2019\bin\test.exp

after_build:
  - cd .build/win32_vs2019/bin
  - md ..\lib\bgfx
  - mv *.lib ../lib/bgfx
  - rm *.pdb
  - rm *.exp
  - rm -r ../obj
  - cp -r ../../../include ..

# Do not run unit tests
test: off

# Package artifacts
artifacts:
  - path: bgfx\.build\win32_$(_TOOLSET)
    name: ${_RELEASE_NAME}
    type: zip

# Create a GitHub release for every tag
deploy:
  # Deploy only when new tags are pushed
  - provider: GitHub
    tag: ${appveyor_repo_tag_name}
    release: ${_RELEASE_NAME}
    artifact: ${_RELEASE_NAME}
    auth_token:
      secure: SXUyBqg8+wl9fn3xHV2Br0xDH65EyPAnFwJbwcg94wIesv9osQEefC3zxu9iDTUh
    on:
      _IS_BUILD_CANARY: false
  # Deploy on each commit
  - provider: GitHub
    tag: ${appveyor_repo_tag_name}
    release: ${_RELEASE_NAME} v${appveyor_build_version}
    artifact: ${_RELEASE_NAME}
    prerelease: true
    force_update: true
    auth_token:
      secure: SXUyBqg8+wl9fn3xHV2Br0xDH65EyPAnFwJbwcg94wIesv9osQEefC3zxu9iDTUh
    on:
      _IS_BUILD_CANARY: true
    description: |
      This is a canary build. Please be aware it may be prone to crashing and is NOT tested by anyone. Use this build AT YOUR OWN RISK!
